### ISSUE TITLE
Medida de cada alimento

### ISSUE THREAD

**Issue by glauberfc** [raulfdm/taco-api#2]
Você pretende atualizar a API adicionando a medida de cada alimento?
Ex.: Alimento - Maçã com casca
       Medida - unidade pequena

**Comment by raulfdm** [comment]
Fala @glauberfc , tudo certo?

Então, o objetivo da API é refletir os resultados da pesquisa realizada pela Unicamp com relação ao valor nutricional dos alimentos. Assim, as medidas, métodos e dados em geral foram gerados 100% por eles. O que a API tenta fazer é transmitir esses dados em um formato que seja mais amigável para desenvolvedores, pois, as versões liberadas por eles são formatos em planilha do excel e pdf.

Ainda pretendo refaze-la, melhorando a estruturação dos dados e adiconando alguns outros que faltaram, mas infelizmente o site deles não está online mais e eu não encontrei uma versão em excel sem alterações. 

Espero que tenha esclarecido sua dúvida.

**Comment by glauberfc** [comment]
Eu entendo, mas você sabe se eles utilizaram uma medida única para cada alimento? Por exemplo: os valores nutricionais são baseados na medida de 100g para cada alimento.

**Comment by raulfdm** [comment]
Oi @glauberfc . Agora entendi sua pergunta. Sim, TODOS os alimentos são 100g, segundo a própria tabela fornecida.

**Comment by olixis** [comment]
<3 @raulfdm

**Comment by raulfdm** [comment]
Essa informação foi adicionada na nova versão que está por vir :)

https://github.com/raulfdm/taco-api/pull/18

**Comment by raulfdm** [comment]
@glauberfc @olixis Nova versão da API atualizada!

https://taco-food-api.herokuapp.com/

Acho que agora vai ficar bem mais fácil com a documentação e também eu adicionei informações faltantes como `acidos graxos (fatty_acids)` e `aminoácidos (amino_acids)`.

**Comment by andre-colognesi** [comment]
Não é possivel pesquisar pelo nome do alimento?

**Comment by luizxx** [comment]
Olá, a sua api ainda funciona? estou montando um programa e precisaria muito dela..

**Comment by raulfdm** [comment]
> Não é possivel pesquisar pelo nome do alimento?

Infelizmente não... quando construi ela, fiz o mais básico possível, mas seria relativamente fácil de implementar essa funcionalidade

**Comment by raulfdm** [comment]
> Olá, a sua api ainda funciona? estou montando um programa e precisaria muito dela..

@luizxx ela está sim, porém, recomendo você fazer um fork dela e subir sua propria versão no Heroku ou em qualquer plataforma.

Digo isso porque como faço uso da versão gratuíta do Heroku para fazer host da API, o servidor hiberna a cada 30 minutos e tem quota de 1000 horas online todo mês, que é divida com outros projetos pessoais.

Então pra evitar contratempos, forka e faz você mesmo o host. :)

**Comment by sidneiJr1984** [comment]
Boa tarde.... você descontinuou a api? ela esta off?

**Comment by raulfdm** [comment]
@sidneiJr1984 https://taco-api.netlify.app/#a-api-esta-offline
