### ISSUE TITLE
Please fix your files

### ISSUE THREAD

**Issue by feciklua** [raulfdm/taco-api#20]
Please consider changing
these [Line]Column values:
-----
[274] Descrição dos alimentos
 raufM(Abadejo, filé, congelado,cozido)
 david(Abadejo, filé, congelado, cozido)
[298] Descrição dos alimentos
 raufM(Lambari, fresco,cru)
 david(Lambari, fresco, cru)
[315] Descrição dos alimentos
 raufM(Salmão, filé, com pele, fresco,  grelhado)
 david(Salmão, filé, com pele, fresco, grelhado)
[373] Piridoxina (mg)
 raufM(,0,02)
 david(0.02)
[468] Descrição dos alimentos
 raufM(Maria mole)
 david(???)
[category]
 raufM (Frutas e derivados)
 david (Frutos e derivados)
----------------------
These 3 first items concerns to:
* Labels.

These other 2 are serious:
* Number-value ,0,02 ---> 0.02
(in xls is still ,0,02)
(in pdf it is corrected to 0.02)
* and to Food-name, that is different
depending on which table:
Number 468 have different food
names between the 3 original tables.
("Maria mole" here, and
"Queijo, requeijão, cremoso" there)

This other 1 item concerns to category:
* "Frutos" are fruits in general.
"Frutas" means sweet-fruits only.
(banana, manga, etc., are sweet ones)
(abacate, pitanga, etc, are not sweet)
(this category-name differs between tables)
("frutos" here, "frutas" there)
------
And congrats for your .CSV
cause it shines a lot.
You just need to clean it:
remove all [^ -þ] characters
from that file.
(chars below space/32 or above þ/254)
-----
Your JSON sucks:
You've lost some important
data from your shinny CSV.
(zero-value matters, because have
different meaning from no-value)
(any-value means: research
was done and presented an value)
(no-value means: tests of that kind
was not required/asked/done)
-----
I'm sorry for my "english":
it sucks a lot.
------
Your .xlsx is almost the same than .csv,
except that .csv fixed "lipid" and "thiamine".
-----
Peace, and congrats.
I've made my own merge from the xls/pdf,
and compared it to your tables.
Thats how I know your tables are well done.
------
Please, tell me:
Today (2018), their website keep
pdf/xls files with rounded values.
Where did you get non-rounded values?

**Comment by raulfdm** [comment]
Hey @feciklua .

Really appreciate the analysis you did and I'll take a look in the data consistency.

It might have issues indeed because the table itself was way tricky to handle.

> Please, tell me:
Today (2018), their website keep
pdf/xls files with rounded values.
Where did you get non-rounded values?

So, the pdf itself is rounded for sure but if you go do `xls` table and inspect the true value of the field you'll see that `excel` or `google sheets` do this conversion for them. Maybe my mistake was instead get the rounded values enforce the exact one and then some values were broken.

**Comment by feciklua** [comment]
Thanks for answering.
I'm glad.
Now I can rest.

**Comment by feciklua** [comment]
Keep your original values!
Rounded values sucks!
(that was my mistake)
----
Keep all values where it appears.
If zero happens dont replace for "".
(hidding values made .Json to fail)

**Comment by feciklua** [comment]
Raulf,
-
[185] threonine_g
 raufM(a)
 david(0.020361912)
-
And please forget about [^ -þ] that I've mentioned.
Because its an single-character to be removed:
0x0D (14 in decimal) at right-side in every line.
-
Using precise values as you told me to,
numerical differences disappeared :)

**Comment by feciklua** [comment]
# Parecia estranho:
id|Verduras, hortaliças e derivados
---|---
140 |Pão, de queijo, assado
141|Pão, de queijo, cru

Mas fui [pesquisar](http://m.tudogostoso.com.br/receita/12621-pao-de-queijo-da-tia-sonia.html),
E apareceu __a (ou uma?) receita dele__:
* 4 xícaras (chá) de polvilho doce
* (...)

Hum... existe:
`146","Polvilho, doce","Verduras, hortaliças e derivados"`

Mas o que é *polvilho*? :rage: 
## Diz o ~~sábio~~ Wikipedia:
> O polvilho, também chamado de fécula de mandioca, carimã ou goma, é o amido da mandioca.
## "Me dá imagens, me dá imagens!"
![polvilho](https://assets.xtechcommerce.com/uploads/images/medium/2b667bbff053f2affa1529970516d718.jpg)

#### Concluindo:
- [x] Aprendi o Markdown, Senhor @raulfdm !
- [ ] Preciso deletar esse comment. :rofl:
