### ISSUE TITLE
A API já contempla todos os alimentos da planilha da UNICAMP?

### ISSUE THREAD

**Issue by alcfernandes** [raulfdm/taco-api#3]
Olá.

A API já contempla todos os produtos da planilha da UNICAMP (4a edição 211)?

**Comment by raulfdm** [comment]
Olá @alcfernandes.

Sim, estão. Porém, estão faltando algumas informações mais minuciosas dos alimentos.

**Comment by Brunolimaa** [comment]
Nessa lista é possível encontrar alimentos não derivados ao leite? Se sim, qual parâmetro devo usar para a consulta?

**Comment by raulfdm** [comment]
Fala @Brunolimaa .

Fiz esse projeto tem muito tempo e na época eu nem pensei em filtrar por categoria.

Retomei ele agora e vou dar uma mudada na API e adicionar parametros pra filtrar.

**Comment by raulfdm** [comment]
https://github.com/raulfdm/taco-api/pull/18

**Comment by raulfdm** [comment]
@Brunolimaa A API foi refatorada e já conta com o filtro por categoria.

Você pode ver a documentação aqui https://taco-food-api.herokuapp.com/

**Comment by raulfdm** [comment]
@alcfernandes Todos os alimentos estão disponíveis na nova versão e com os ácidos graxos e também aminoácidos (que faltavam na versão anterior)! :)

**Comment by Brunolimaa** [comment]
@raulfdm desculpa a pergunta, voce saberia me informar se tem alguma categoria referente a alimentos zero lactose?

**Comment by raulfdm** [comment]
@Brunolimaa não bruno, infelizmente não. 

O projeto da TACO não contempla essa categoria.

**Comment by dinhopenna001** [comment]
Boa Noite Posso usar sua api para um projeto pessoal de um aplicativo?

**Comment by raulfdm** [comment]
Fala @dinhopenna001... respondi essa dúvida aqui: https://github.com/raulfdm/taco-api/issues/2#issuecomment-890807811
