### ISSUE TITLE
Posso utilizar esta api em um aplicativo?

### ISSUE THREAD

**Issue by Maithe** [raulfdm/taco-api#4]
Gostaria de utilizar esta api em um aplicativo, isso seria possível?

**Comment by raulfdm** [comment]
Olá Maithe.

Então, eu fiz esse projeto tem muito tempo, preciso retoma-lo para ver onde eu parei.

Eu sei que por hora o servidor não está online e os alimentos lá ainda estão faltando os índices de ácido graxo e os aminoácidos.

Vou pegar pra trabalhar nele nesse final de semana e te aviso! :)

**Comment by raulfdm** [comment]
https://github.com/raulfdm/taco-api/pull/18

**Comment by raulfdm** [comment]
@Maithe A API foi refatorada e já pode ser usada! :)

Documentação disponível: https://taco-food-api.herokuapp.com/
