### ISSUE TITLE
Server nao roda

### ISSUE THREAD

**Issue by marcuscaum** [raulfdm/taco-api#74]
Depois de rodar `bun run dev --filter=taco-api` o server nao fica em aberto na porta 4000 como a wiki diz. O output ta ai na imagem.

<img width="833" alt="image" src="https://github.com/raulfdm/taco-api/assets/5979318/e8a6ab4b-7bf9-4627-8756-3bb54f02aa09">

**Comment by mcaxtr** [comment]
tenta 

`bun run start --filter=taco-api`

**Comment by marcuscaum** [comment]
`error: Missing script "dist/app.js`

**Comment by marcuscaum** [comment]
como resolve?

**Comment by raulfdm** [comment]
@marcuscaum qual a versão do bun que você ta rodando?

Roda um `bunx envinfo --system --binaries` e cola aqui o resultado.

Também me descreve o passo-a-passo que você fez pra chegar nesse erro. Sem detalhes não consigo ajudar.

Eu removi completamente o projeto, dei clone, rodei `bun install` e depois `bun run dev --filter=taco-api ` e ta rodando normal aqui. Por isso preciso detalhes

**Comment by raulfdm** [comment]
> `error: Missing script "dist/app.js`

Talvez você esteja com uma versão antiga do repositorio

**Comment by raulfdm** [comment]
Fique à vontade pra reabrir quando tiver mais informações.
